[package]
name = "rust_autogpt_agents"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
dotenv = "0.15.0"
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version="1.0.203", features = ["derive"] }
tokio = { version = "1.38", features = ["full"] }
